language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=${PYTHONPATH}:/home/travis/build/Went-Yang/emis-backend

script:
  - python tests/unittest/test_knowledge_service.py
